Repository BioMedIA/deepali, pull requests merged in 2022-11, with the labels that each got.

#30 enh: Rename image transformer module Grid accessors; add ImageTransform.condition() setters
  src/deepali/modules/sample.py
  src/deepali/spatial/image.py
Labels: enhancement

#31 fix: Grid issues identified by static code analyzer
  src/deepali/core/grid.py
  src/deepali/core/tensor.py
Labels: bug

#32 fix: Missing 'u' or 'v' in named_buffers()
  src/deepali/spatial/nonrigid.py
Labels: bug

#33 enh: Add remove_layers_in_state_dict() and enable removing prefix when renaming layers
  src/deepali/modules/__init__.py
  src/deepali/modules/utilities.py
Labels: enhancement

#35 doc: Check mark to reflect that MI and NMI losses are available
  TODO
Labels: documentation

#36 enh: Add jacobian_det() function to core
  src/deepali/core/flow.py
  src/deepali/core/functional.py
Labels: enhancement

#37 fix: Type annotation of Cube and Grid from_numpy()
  src/deepali/core/cube.py
  src/deepali/core/grid.py
Labels: bug

#38 enh: Add Dice loss module
  src/deepali/losses/__init__.py
  src/deepali/losses/image.py
Labels: enhancement
